on:
  workflow_dispatch
  
name: buildSite
jobs:
  buildgeoLabWebsite:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        id: buildCheck
        run: |
             git clone https://github.com/wmgeolab/geolabWeb
             pwd
             ls
       
      
