on:
  workflow_dispatch
  
name: buildSite
jobs:
  buildgeoLabWebsite:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        id: buildCheck
        run: |
             git clone https://github.com/wmgeolab/geolabWeb
             pwd
             ls
      - name: Build Files
        id: buildFiles
        run: |
              pip install pandas
              python /home/runner/work/geolabWeb/geolabWeb/geolabWeb/assets/python/generateProjectsPeople.py
              ls
              ls geolabWeb
              ls geolabWeb/_posts/projects
      - name: Push Updates
        id: pushUpdates
        env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
             cd geolabWeb
             git config --global user.name 'DanRunfola'
             git config --global user.email "DanRunfola@users.noreply.github.com"
             git add -A .
             git commit -m "Automated Build"
             git push
             
       
      
