on:
  workflow_dispatch
  
name: buildSite
jobs:
  buildgeoLabWebsite:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        id: buildCheck
        run: |
             git clone https://github.com/wmgeolab/geolabWeb
             pwd
             ls
      - name: Build Files
        id: buildFiles
        run: |
              pip install pandas
              python /home/runner/work/geolabWeb/geolabWeb/geolabWeb/assets/python/generateProjectsPeople.py
              ls
              ls geolabWeb
              ls geolabWeb/_posts/projects
      - name: Push Updates
        id: pushUpdates
        env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           DRTOKEN: ${{secrets.DRTOKEN}}
        run: |
           cd geolabWeb
           git config --local user.email "danr@wm.edu"
           git config --local user.name "DanRunfola"
           git fetch
           git add -A .
           git remote set-url origin https://x-access-token:${{ secrets.DRTOKEN }}@github.com/$GITHUB_REPOSITORY
           git diff-index --quiet HEAD || git commit -m "Automated Build"
           git status
           git push origin main 
             
       
      
