on:
  workflow_dispatch
    
name: DeployWebsite
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: Download Changes
      uses: actions/checkout@v2
      with:
        repository: wmgeolab/geolabWeb
        ref: gh-pages
             
    - run: |
           ls -l
           cd geolabWeb
           ls -l
